SmartlyDressedGames/U3-Docs

- CuratedMaps.md
Early revision for a "Eligibility for Curation" section. Could likely be trimmed down somewhat to be more direct.
> Update CuratedMaps.md for Eligibility section

- CharacterMeshReplacement.md
Fixed two typos, cleaned up whitespace inconsistencies, and general English structure (my forte!).
> Copyediting.

- ServerHosting.md
Comprehension (for the "Name" input) and English fixes.
> Minor clean-ups

- CuratedMaps.md
> Capitalization

- AssetBundles.md
"etc" --> "etc." ; comma between participle phrase and main clause ; replaced peculiar whitespace
> Copyediting

- README.md
Created a separate section for Server tutorials, and linked PortForwarding.md
> Servers section

- NPCAsset/Characters.md
- NPCAsset/README.md
Subdirectory for NPC asset information—this would include characters, conditions and rewards, dialogues, vendors, and quests. Two files are included in this pull request, which are located in this new subdirectory.
The README file provides an explanation as to what NPCs are, in terms that are relevant to modders. The file also covers text formatting tricks unique to NPC localization files.
The Characters file covers properties and localization as it pertains to NPC characters. Appearance, clothing, held items, and other properties.
> NPC Character properties

- NPCAsset/Vendors.md
> NPC Vendors

- ItemAsset/Actions.md
- ItemAsset/Blueprints.md
Dedicated documentation files for blueprints and actions.
> Blueprints and Actions

- NPCAsset/Characters.md
- NPCAsset/Vendors.md
Fixes links to GUID.md. Updates the Characters.md file to link to Conditions.md, as NPC characters can be made to only appear to a player while they meet certain conditions.
> Hyperlink fixes

- AnimalAsset.md
Documentation for animal assets. Many of these properties aren't used in official content, so please review for accuracy of descriptions.
What would a good description for Should_Play_Anims_On_Dedicated_Server be?
> Animal asset documentation

- ServerHosting.md
Added the Workshop ID for the curated Ireland map.
> Ireland Workshop ID

- SpawnAsset.md
Spawn asset type documentation.
> Spawn assets (spawn tables)

- ModHooks.md
Activa**ton** Event Hook --> Activa**tion** Event Hook
> ModHooks.md typo fix

- ItemData.md
Added Experience modifier for consumeable items from 3.21.24.0 update.
> Experience modifier line from 3.21.24.0 Update.

- ItemAsset/MapAsset.md
- ItemAsset/README.md
- ItemAsset/SupplyAsset.md
Documentation for ItemMapAsset and ItemSupplyAsset.
> MapAsset and SupplyAsset docs

- GUID.md
Added a note that the game will automatically try to assign a random GUID during load, if the asset is loaded successfully.
> random GUID assigned during load

- NPCAsset/Vendors.md
> Vendors can use NPC Rewards

- ItemAsset/BarricadeAsset.md
> Allow_Placement_Inside_Clip_Volumes

- ItemAsset/ConsumeableAsset.md
- Lowers a heading level down by 1.
- Fixes typo for Consumeables documentation.
> Minor formatting tweaks

- EffectAsset.md
Documentation for the upcoming CameraShake properties available for Effect assets.
> CameraShake properties

- CommandLine.md
Relevant for troubleshooting if OpenGL is launched by default
> -force-vulkan Command

- NPCAsset/Rewards.md
Expanded description. Listed the default enumerator. Listed all enumerators that can be used.
> Added more info about Reward_#_Origin

- ItemAsset/README.md
Fixes an internal hyperlink to another doc.
> Fix MasterBundlePtr doc hyperlink

- ServerHostingRules.md
Alter wording if desirable, but the intent is to have links to the support / help center tickets. These links have the issue preselected.
> Links for for filing report/appeal tickets

- ItemAsset/FarmAsset.md
- ItemAsset/FuelAsset.md
[3.23.3.0](https://store.steampowered.com/news/app/304930/view/3672160492276918618) patch.
> Always_Spawn_Full and Affected_By_Agriculture_Skill
