- ItemData.md
* Added disclaimer to melee weapon section regarding lack of documentation.
* Fixed various typos and broken formatting.
* Clarified on how to use Can_Aim_During_Sprint.
* Clarified on more default values.
* Added Recoil_Sprint, Recoil_Crouch, and Recoil_Prone.
* Added Spread_Sprint, Spread_Crouch, and Spread_Prone.
> 3.20.12.2 patch notes + improvements

- OpenMod.md
OpenMod 3 changes the way how OpenMod works with RocketMod. The OpenMod RocketMod Bridge has been removed and there is no need to install any OpenMod plugins for RocketMod support.  OpenMod and RocketMod can now co-exist without issues (OpenMod will now dynamically patch RocketMod's command handling and logging if is installed).
~~Will be draft until OpenMod 3 releases. At the moment it is being tested.~~
OpenMod 3 has released now: https://github.com/openmod/openmod/releases/latest
> RocketMod Compatibility changes from OpenMod 3

- ItemData.md
Adds documentation for Proof_Fire, Proof_Water, and Proof_Radiation. Also includes an clarificatory example for "limb-independent entity damage".
> Proof_* properties

- GUID.md
Changed "32 digit numbers" --> "32 hexadecimal digits"
Technically the original wording isn't wrong when thinking about binary, but hexadecimal is still more accurate as to what a GUID is composed of.
> GUIDs are composed of 32 hexadecimal digits

- ServerHostingRules.md
Original wording was from before the rules were in full effect, and referenced dates as if they were yet to come. New wording is reflective of the rules having been in full effect since June 2021.
> Changed tense of dates for monetization rules

- NPCAsset/Conditions.md
- WeatherAsset.md
Implements an up-to-date version of the Conditions section from the original official [Steam Guide](https://steamcommunity.com/sharedfiles/filedetails/?id=784254150) on modding NPCs. Includes documentation for all condition types, including the weather conditions that are currently documented in WeatherAsset.md.
Updates the "NPC Conditions" subheading of WeatherAsset.md, to redirect modders to Conditions.md.
The only property I am wholly uncertain of is **Condition\_#\_Ignore\_NPC** *bool*. What is its purpose? None of the official nor curated maps seem to make use of it. It is a property useable by Quest conditions, and is presumably on important for the Ready state of the quest.
> NPC quest conditions

- Currency.md
Redirects documentation on Currency type NPC logic to the Conditions.md and Rewards.md files.
> Redirect currency "NPC Logic"

- ItemAsset/README.md
ItemAsset directory for new, updated Item asset documentation. This pull request includes the README.md file for the directory, which contains all universal/general properties for item assets. Ideally, we eventually fully phase out ItemData.md in favor of the ItemAsset directory.
Technically, **Ignore_TexRW** is just a general asset property, rather than a unique item asset property. We could move this to [AssetsV1.md](https://github.com/SmartlyDressedGames/U3-Docs/blob/master/AssetsV1.md) instead, if that would make more sense.
With a file per item type, there would be 48 files additional files in this directory, plus an additional two for actions and blueprints. We could perhaps reduce this by combining clothing together, consumables together, and economy types together, but I think …
> ItemAsset directory

- NPCAsset/Dialogues.md
Documentation for NPC dialogue assets. Serves as a replacement of the original Steam Guide documentation for NPCs.
> Dialogues.md

- CommandLine.md
Documents launch arg to disable Steam text filter and instead revert to the old naïve filter.
> NoSteamTextFiltering launch arg

- ItemAsset/BarrelAsset.md
- ItemAsset/GripAsset.md
- ItemAsset/MapAsset.md
- ItemAsset/README.md
- ItemAsset/SightAsset.md
- ItemAsset/TacticalAsset.md
Creates the **BarrelAsset.md** and **GripAsset.md** documentation files for barrel attachments and grip attachments.
Revises all other attachment documentation to separate CaliberAsset properties from the item's unique properties. Added missing CaliberAsset properties.
Copyediting for any other ItemAsset documentation files with new commits.
> ItemAsset documentation (Grips/Barrels, +revisions)

- ItemAsset/BarrelAsset.md
- ItemAsset/GripAsset.md
- ItemAsset/SightAsset.md
- ItemAsset/TacticalAsset.md
Adds two caliber asset properties that were missing from the four attachment asset docs. 
**Calibers** *uint16*: Total amount of unique calibers.
**Caliber_#** *uint16*: Caliber ID for acceptable attachment compatibility.
> Add missing Calibers and Caliber_# properties

- ItemAsset/SentryAsset.md
As per the 3.21.33.0 Update (sentry guns do not lose targets immediately outside detection radius).
> Target_Loss_Radius

- CommandLine.md
HW abbreviation for Halloween, and AprilFools for April Fools' Day.
> Added missing acceptable holiday strings

- ItemData.md
Adds a note to the top of ItemData.md, which tells readers that this doc file is deprecated, and up-to-date docs can be found in the ItemAsset directory.
> Hatnote to redirect readers to the updated docs

- CommandLine.md
Command for disabling the loading of all Steam Workshop subscriptions. This can be helpful when troubleshooting issues.
> -NoWorkshopSubscriptions

- ItemAsset/BarrelAsset.md
- ItemAsset/CaliberAsset.md
- ItemAsset/GripAsset.md
- ItemAsset/MagazineAsset.md
- ItemAsset/MapAsset.md
- ItemAsset/SightAsset.md
- ItemAsset/SupplyAsset.md
- ItemAsset/TacticalAsset.md
Moves documentation of **Caliber Assets** out of docs such as **SightAsset.md** and **GripAsset.md**. Instead, creates a new doc called **CaliberAsset.md**.
Then, adds a "**This inherits the XYZ class.**" note to the lead section of each item asset, which links to its parent class.
The latest commit only lists the direct parent, and doesn't take into account multilevel inheritance (e.g., GripAsset → CaliberAsset → ItemAsset). But, we could change this so that all relevant parents are taken into account, if you feel that'd be more helpful.
I.e., "**This inherits the CaliberAsset, and ItemAsset classes.**"
---
**Further thoughts:** My thought process with creating CaliberAsset.md is that this will reduce repeated/duplicate information, and thus make maintaining the docs simpler. Classes …
> CaliberAsset.md and inheritance

- ServerHosting.md
Adds the Arid map to the list of Workshop IDs in the server hosting guide.
> Arid workshop ID

- ItemAsset/ConsumeableAsset.md
- ItemAsset/FoodAsset.md
- ItemAsset/MedicalAsset.md
- ItemAsset/WaterAsset.md
- ItemAsset/WeaponAsset.md
Documentation for consumables.
Regarding the **WeaponAsset.md** file specifically... Is there a better term for grouping barricades, structures, vehicles, resources, and objects together? Maybe ***world***, ***environmental***, or ***props***? (The doc currently uses ***constructs***.)
I've traditionally used terms such as *constructs*, but this is technically already used by structures. I've also used *non-entities*, but I'm not sure if that'd actually be accurate. For comparison, I typically group animal/player/zombie as *creatures*.
> Documentation for consumable items

- NPCAsset/Conditions.md
- NPCAsset/Rewards.md
Fixes the data type listed for the **Conditions** and **Rewards** properties. Now, lists them as a *byte*.
Lists out all of the members of the **_Type** enumerated types.
Adds a note to the top of each doc file, which clarifies that the specific names/prefixes of the properties may differ between assets. E.g., **Blueprint_#_Rewards** for blueprints and **Quest_Rewards** for consumables.
> Fixed data type, listed enumerators, & prefixes/names clarity

- NPCAsset/Rewards.md
Added vehicle reward clarification (Information taken from https://steamcommunity.com/sharedfiles/filedetails/?id=784254150)
The current wording is probably a miscopy from Teleport section.
> Vehicle section in Rewards.md

- AssetBundles.md
*Significantly* trims down the "Content Bundles" section. (Removes the steps for creating content bundles, and motivations behind content bundles.)
Adds a brief section on how to reuse content bundles. I believe the provided explanations are factually correct?
> Brief steps on reusing content bundles

- EffectAsset.md
- ItemAsset/Actions.md
- ItemAsset/BarrelAsset.md
- ItemAsset/Blueprints.md
- ItemAsset/CaliberAsset.md
- ItemAsset/ConsumeableAsset.md
- ItemAsset/GripAsset.md
- ItemAsset/MagazineAsset.md
- ItemAsset/MapAsset.md
- ItemAsset/SightAsset.md
- ItemAsset/TacticalAsset.md
- ItemAsset/WeaponAsset.md
- NPCAsset/Characters.md
- NPCAsset/Conditions.md
- NPCAsset/Rewards.md
- NPCAsset/Vendors.md
- SpawnAsset.md
Changes the listed data type for many properties from _bool_ to _flag_. Should be less confusing. In some cases, also modifies the description of the property to be slightly more concise.
Includes some misc. corrections to other non-flag properties, and adds data types to properties missing one.
> Flags (bool → flag)

- ItemAsset/README.md
This PR adds the `Pro` flag property to the documentation.
----
I have some confusion regarding what I'm looking at in regards to ItemAssets. There appears to be both a "**Is_Pro**" _boolean_ property, and a "**Pro**" _flag_ property.
Item .dat files only ever reference the "Pro" flag property. What is the other property? Is it relevant to have on the docs?
> Pro flag and IsPro boolean?

- ItemAsset/README.md
This PR removes Is_Pro documentation, based on additional information provided from #157. 
Is_Pro is from a partial rewrite -- safe to exclude from docs.
> Remove Is_Pro boolean

- ItemAsset/OpticType.md
- ItemAsset/SightAsset.md
Documentation for optic assets. Includes an update to SightAsset.md as well, to clarify that zoom should be set to a value greater than 1.
Technically, the "Zoom" data type for optics isn't a float _right now_, but _it will be_ as of the next mainline game update.
> Optic assets + scope zoom

- ItemAsset/README.md
- ItemData.md
Some people still use this deprecated documentation file. These commits are intended to further phase the deprecated file out.
The deprecation notice has been made more noticeable. Any deprecated documentation that has been fully superseded by new material has been replaced with links to the new documentation files.
Also, includes a minor fix changing the newer documentation of **Ignore_TexRW** from **_bool_** to **_flag_**.
> Further phasing out of ItemData.md

- CuratedMaps.md
Includes various additions/improvements/tweaks to curation guidelines for clarity.
**Important:** also includes a rough first pass at writing guidelines on age appropriacy (i.e., family friendly content). I've primarily focused on implementing the main points from our discussions, but please review thoroughly.
- **Added guidelines on age appropriacy—that is: profanity, drugs/alcohol, and NSFW content guidelines.**
- Added guidelines regarding playtime drops. **Reasoning:** newer curated maps usually release with free playtime drops, in addition to paid Stockpile bundles. **Note:** technically, precedent would put the range at "ten to thirty items", but that's merely because of Elver2 releasing with 28 items. Unsure if this is an outlier, or if 10-30 is more accurate.
- Clarified the item …
> Further clarify curation guidelines

- NPCAsset/Conditions.md
"None" was missing from the list. Also, reordered based on the order of progression
> "None" enumerator for quest status condition

- ServerHosting.md
A common complaint about server hosting is that people think SteamCMD is **_required_** to host the server. This rewords the intro to clarify that SteamCMD is ideal for multiple servers, but otherwise optional, and that some of the documentation may not apply to those who aren't using SteamCMD.
> Reworded to clarify SteamCMD is optional

- ItemAsset/GunAsset.md
- ServerHosting.md
- Removed `Durability` from GunAsset docs, as it's a WeaponAsset property.
- Rearrange order of the server doc's Table of Contents to better match the actual order of section headings.
- Corrected information about `Recoil_Aim` in the gun docs.
For the final bulleted item, note that you've described this as being a reduction with a value 0–1. However: using a value outside greater than 1 works in-game (greater than 1 causes increased recoil), so I'm unsure if this is actually constrained to a value 0–1.
> Patch minor fixes

- ServerHostingRules.md
It appears that this important context is being lost during translation. This edit increases the emphasis by formatting the original line, and adding a "banned monetization" that more explicitly states vanilla cosmetics cannot be sold.
> Emphasis on only *CUSTOM* cosmetics being sellable

- CuratedMaps.md
Expands the "Bundles" prep info to include info on the two collection types (an assortment of loosely-related items, or a complete outfit). Advises against having multiple items that take up the same cosmetic slot.
> Avoid outfits w/ duplicate cosmetic slots

- ServerUpdateNotifications.md
The channel is just called "#dedicated-server-updates".
> Fixes Discord channel name

- ZombieDifficultyAsset.md
Adds a documentation file named **ZombieDifficultyAsset.md**.
Note: although the official/vanilla ZombieDifficulty.asset files have an "ID" property, this isn't used by the class and the asset file works fine without it, so I haven't included it on the documentation.
> ZombieDifficultyAsset

- CommandLine.md
The disambiguation is probably confusing (& not that relevant, to be honest). Linking directly to the arguments from the Unity Standalone Player instead is better.
> Change Unity link from disambig to list

- CommandLine.md
Does this only apply to vehicles now?—does a note about that need to be added here?
> -ForceTrustClient flag

- ServerHostingRules.md
This PR does the following:
1. Adds a section for listing recent updates, rather than just adding them to the top of the doc. Currently, this just contains the "October 16, 2022 clarification" about skin changers.
2. Adds a section about deceptive pricing, and moved the relevant information from the "August 2, 2021 update" snippet into it.
3. Adds a new section for monetization examples, and moves the preexisting lists into it.  Clarifies that the list is not intended to be exhaustive.
4. Clarifies on banned item/vehicle consumables (the ability for them to be permanently lost, stolen, or destroyed).
5. Greatly expands on the "Monetization Filter" section. The lead contains general information about the field and how players can use it. There are now three subsections beneath – one for …
> Expand on wording of MTX rules

- PortForwarding.md
Update the port forwarding doc with port forwarding alternative (tunneling) with https://playit.gg.
I'm the creator of https://playit.gg and have found there's quite a few people using us to host Unturned servers. Not sure if this is the right place or if mentioning third party applications is okay.
The service is free and supported by users purchasing custom domains or dedicated IPs.
YouTube videos showing how to do it
(updated) https://www.youtube.com/watch?v=eSk73ELAp1s
(original) https://www.youtube.com/watch?v=Jqmgruvamd4
> Add tunneling instructions to port forwarding

- ItemData.md
This commit removes a bunch of outdated info from ItemData.md, that has since been superseded by the info available from the ItemAsset directory. (Continuing with the goal of moving away from using this file for item asset documentation.)
> Remove outdated info from ItemData.md

- AnimalAsset.md
- AssetBundleCustomData.md
- AssetBundles.md
- Bitmask.md
- EditorAssetRedirectors.md
- EffectAsset.md
- Foliage.md
- GameServerLoginTokens.md
- Glazier.md
- ItemAsset/BarricadeAsset.md
- ItemAsset/FuelAsset.md
- ItemAsset/GripAsset.md
- ItemAsset/README.md
- Layers.md
- LevelAsset.md
- LevelBatching.md
- ManualObjectCulling.md
- ModHooks.md
- OpenMod.md
- PhysicsMaterialAsset.md
- Rocket.md
- RocketMod.md
- ServerHostingRules.md
- ServerUpdateNotifications.md
- SpawnAsset.md
- Troubleshooting.md
- Unity2018.md
- Unity2019.md
- WeatherAsset.md
Adjusts the markup for Lv1 and Lv2 headings so that – if we decide to use .rst instead of .md instead – most files will already be ready and functional. Also: this PR adds headings for any docs that didn't already have one.
None of the commits include markup that doesn't work with .md, so nothing will break.
> Adjust heading markup for .RST
